# Generated by Django 4.1 on 2022-08-29 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0005_rename_user_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="likes",
            field=models.ManyToManyField(
                related_name="photo_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
